### ISSUE TITLE
Extract normalized expression matrix

### ISSUE THREAD

**Issue by GeremyClair** [DavisLaboratory/standR#12]
Hi there, 
I would like to retrieve the normalized expression as a simple data frame after performing the normalization in StandR can you guide me on how to do this.
Thank you in advance for your help
Geremy Clair

**Comment by ningbioinfo** [comment]
Hi Geremy,

Assuming you're doing normalization using `spe <- geomxNorm(spe, method = "TMM")`
You can do `df <- assay(spe, "logcounts")` or `df <- assay(spe, 2)` to get the norm count table.

**Comment by GeremyClair** [comment]
Thank you for your answer, it is appreciated. I was able to figure from your code that you were using EdgeR for the normalization. I therefore performed the normalization outside of the spatial object, but this is good information for the next time around!
