### ISSUE TITLE
plotScreePCA and plotPCAbiplot with reducedDim 

### ISSUE THREAD

**Issue by joonlee3** [DavisLaboratory/standR#13]
Hi,

   When I ran `plotScreePCA` or `plotPCAbiplot` with a precomputed dimensional reduction, I've got an error.
`
> spe              <- scater::runPCA(spe)
> pca.results <- reducedDim(spe, "PCA")
> plotPCA   <- drawPCA(spe, precomputed=pca.results, col=Annotation, shape=SlideName)
> plotScreePCA(spe, precomputed=pca_results)
Error in checkPrecomputedPCA(spe_object, precomputed) : 
  all(rownames(pcdata) == colnames(object)) is not TRUE
In addition: Warning message:
In rownames(pcdata) == colnames(object) :
  longer object length is not a multiple of shorter object length
`
Any suggestions? Thanks.

Best,
Joon

**Comment by ningbioinfo** [comment]
Hi Joon, 
I think what you want is `plotScreePCA(spe, precomputed=pca.results)`.
Apparently you have an object named pca_results that has different dimension than the spe.
