### ISSUE TITLE
removebatcheffect removal and normalization

### ISSUE THREAD

**Issue by dksenthil** [DavisLaboratory/standR#14]
Hi, Usually batch effect correction will involve only the slide name. I'm my case I will have to do for "reagent_lot_ID+SlideName".
I followed the workshop Vignettes here https://davislaboratory.github.io/GeoMXAnalysisWorkflow/articles/GeoMXAnalysisWorkflow.html.
In the vignettes, I noticed that batch-correction and RLE is done on **spe**  object and not  on the normalized **spe_TMM** 
I want to confirm if batch correction can be done after doing normalization.

**Comment by ningbioinfo** [comment]
Yes, in the document batch-correction is done on spe not the spe_tmm. RLE is used to check if technical variations are removed or not.
Batch-correction process is also a normalization process, while tmm/size_factor etc correct for library size and other compositional biases, batch-correction is more aggressive process that removes batch-effect in your data. So you need to run batch-correction only when you see batch effects.
PS: you can run batch-correction on tmm-normalised data, in our experience, it would not affect your DE results much compared to running on un-normalised data.
