### ISSUE TITLE
Error in readGeoMx

### ISSUE THREAD

**Issue by knadia07** [DavisLaboratory/standR#16]
I am having some issue reading the <spe <- readGeoMx(countFile, sampleAnnoFile, featureAnnoFile)> which end up with an error  below: 

Error in h(simpleError(msg, call)) :
error in evaluating the argument 'x' in selecting a method for function 'as.matrix': undefined columns selected

**Comment by ningbioinfo** [comment]
Hi @knadia07 , what are your inputs? are they files or objects in R? If latter, can you do:
```
object(countFile)
object(sampleAnnoFile)
object(featureAnnoFIle)
```
to make sure that they are data.frame object (note: not tibble, data.frame).

Moreover, can you paste the result of:
```
colnames(countFile)
colnames(sampleAnnoFile)
colnames(featureAnnoFile)
```
if they are data.frames?

**Comment by MusculusMus** [comment]
similar error:
`Error in [.data.frame(samplemeta_filtered, , coord.colnames) : 
  undefined columns selected`

Here is screenshot of my three input files:
![standr](https://github.com/DavisLaboratory/standR/assets/37739300/67f2f916-afad-47d1-a16c-e25d4ead886a)

I have a mouse WTA data without AOIs, and the `SegmentDisplayName` is the `dcc` file name, Can you specify which columns are needed in each file? Especially the data frame contains the samples' info, my file is missing some columns.

**Comment by ningbioinfo** [comment]
Hi @MusculusMus , yours is a different error to knadia07's. I think the problem of yours is due to the lack of coordinates name, can you do `colnames(sampleAnnoFile)` to see what columns are in your sample annotation file?

**Comment by MusculusMus** [comment]
> colnames(sampleAnnoFile)
 [1] "SlideName"          "ScanLabel"          "ROILabel"           "SegmentLabel"      
 [5] "SegmentDisplayName" "aoi"                "AOISurfaceArea"     "AOINucleiCount"    
 [9] "anima_ID"           "age"                "genotype"           "pathology"         
[13] "Bin1"               "Type"               "RawReads"           "AlignedReads"      
[17] "Reads_dedup"


That is why I would like to know which columns are necessary to construct the proper expression data for this standR workflow.

**Comment by ningbioinfo** [comment]
@MusculusMus , yeah so usually there are two columns "ROICoordinateX" and "ROICoordinateY" in the sample annotation data, even though they are not affecting the differential analysis, it is a key feature of a spatial experiment. If your data don't have those, you can probably make up some coordinates to pass that test.

```
sampleAnnoFile$ROICoordinateX <- seq(nrow(sampleAnnoFile))
sampleAnnoFile$ROICoordinateY <- seq(nrow(sampleAnnoFile))
```

Then rerun the `readGeoMx` function.

**Comment by MusculusMus** [comment]
It works!

**Comment by fedor-grigoryev** [comment]
@MusculusMus Having the similar problem, when trying to follow your tutorial on kidney -- `readGeoMx` fails with
`Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.data.frame': basic_ios::clear: iostream error`

The arguments to the function are all filenames (named strings). Does it sound any familiar?

**Comment by willros** [comment]
Hi @MusculusMus

Just wonder how you created the sampleAnno and featureAnno file for the readGeoMx function? Thanks!
William
