### ISSUE TITLE
Error in readGeoMx qith rmNegProbe = FALSE

### ISSUE THREAD

**Issue by Sigmatilde** [DavisLaboratory/standR#18]
I am trying to run the cellular deconvolution analysis and the 
`readGeoMx(countFile, sampleAnnoFile, featureAnnoFile, rmNegProbe = FALSE)`  is generating the error:

```
Warning: non-unique value when setting 'row.names': ‘NegProbe-WTX’
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
```

**Comment by ningbioinfo** [comment]
Hi @Sigmatilde , there are multiple NegProbe-WTX probes in your data, if you want to retain the negative probes, I would suggest you to change the name of them, e.g. NegProbe-WTX1, NegProbe-WTX2, NegProbe-WTX3.. etc.

**Comment by vmkalbskopf** [comment]
If you change the names of the NegProbe-WTX as you suggested, then I get the error
`Error in geomx_import_fun(countFile, sampleAnnoFile, featureAnnoFile,  : 
  NegProbeName is not found in your count file.`

I changed the names like this:

`count_df <- count_df %>%
  group_by(TargetName) %>%
  mutate(
    TargetName = if_else(
      TargetName == "NegProbe-WTX",
      paste0("NegProbe-WTX-", row_number()),
      TargetName
    )
  ) %>%
  ungroup()       `

**Comment by ningbioinfo** [comment]
Hi @vmkalbskopf , yeah then in readGeoMx, do NegProbeName = paste0("NegProbe-WTX", seq(N_NEGPROB)) # change the N_NEGPROB into your number.

**Comment by vmkalbskopf** [comment]
Hey! Thanks for responding in such an old thread :-)

I get this error:

`Error in if (!NegProbeName %in% as.matrix(countdata[, colnames.as.rownames[1]])) { : 
  the condition has length > 1`

And here is the command for the sake of clarity:

````
spe = readGeoMx(countFile = "extdata/skin/counts.tsv",
                sampleAnnoFile = "extdata/skin/sampleAnnoFile.tsv",
                featureAnnoFile = "extdata/skin/featureAnno.tsv",
                NegProbeName = paste0("NegProbe-WTX-", seq(139)),
                colnames.as.rownames = c("TargetName", "ROI_ID", "TargetName"))
````
Just so you know, I am doing this so I can perform spatial deconvolution.

**Comment by vmkalbskopf** [comment]
My feature annotation file has one row for each negative probe too (all 139 probes).

**Comment by ningbioinfo** [comment]
hi @vmkalbskopf , that seems to be a small bug. Fixed and pushed. Can you try reinstall the devel version in Github by remotes::install_github("DavisLaboratory/standR") and then restart R and try it?

**Comment by vmkalbskopf** [comment]
Thanks, I don't get that error anymore, but a different one which I will post in a new issue.
