### ISSUE TITLE
spatialdecon

### ISSUE THREAD

**Issue by OnkarMulay** [DavisLaboratory/standR#24]
Hi @ningbioinfo ,

Thanks for the tool.

If there are multiple negative probes then 
`bg <- as.data.frame(norm*0)` -> this change needs to be made in the original function.

I'm getting this error on running `spatialdecon` though 
Error in solve.default(fit$hessian): Lapack routine dgesv: system is exactly singular: U[1,1] = 0

Code:
```
res <- spatialdecon(norm = spd$normCount,
                               bg = spd$backGround,
                               X = safeTME,
                               cellmerges = safeTME.matches,
                               resid_thresh = 1,lower_thresh = 0.1)
```

Please let me know how can I solve this issue.
Thanks

**Comment by ningbioinfo** [comment]
Hi @OnkarMulay , if you have multiple negative probes, can you try the `negProbeName` and `pool` parameters from the `prepareSpatialDecon` function?
