### ISSUE TITLE
Error in prepareSpatialDecon(spe_tmm) :  could not find function "prepareSpatialDecon"

### ISSUE THREAD

**Issue by ZoeGerber** [DavisLaboratory/standR#26]
Hello,

I'm currently utilizing your R Package for analyzing NanoString DSP data. I've been following the steps outlined in your workshop, and everything has been functioning correctly until I reached the cellular deconvolution step. The specific section I'm referring to can be found here: [Cellular Deconvolution](https://davislaboratory.github.io/GeoMXAnalysisWorkflow/articles/GeoMXAnalysisWorkflow.html#cellular-deconvolution).

The issue arises when I try to use the prepareSpatialDecon function. Despite following the instructions closely, this function doesn't seem to be recognized, leading to an error. I'm not sure why this is occurring, as I've double-checked the steps and ensured all prerequisites are met.

Here are some details that might help in diagnosing the issue:

```
> library(SpatialDecon)
> spe_tmm <- geomxNorm(spe, method = "TMM")
> spe_tmm
class: SpatialExperiment 
dim: 4028 306 
metadata(5): NegProbes lcpm_threshold genes_rm_rawCount genes_rm_logCPM norm.factor
assays(2): counts logcounts
rownames(4028): PSMC4 DCTPP1 ... RPS13 IL16
rowData names(13): HUGOSymbol TargetGroup ... GeneID genes_lowCount_overNsamples
colnames(306): TMA R3_1 07212022 | 001 | Tumor TMA R3_1 07212022 | 001 | Stroma ... TMA
  R1_2 07192022 | 054 | Tumor TMA R1_2 07192022 | 054 | Stroma
colData names(35): SlideName ScanLabel ... countOfLowEprGene percentOfLowEprGene
reducedDimNames(0):
mainExpName: NULL
altExpNames(0):
spatialCoords names(2) : ROICoordinateX ROICoordinateY
imgData names(1): sample_id
> spd <- prepareSpatialDecon(spe_tmm)
Error in prepareSpatialDecon(spe_tmm) : 
  could not find function "prepareSpatialDecon"
```

Error Message: 
*Error in prepareSpatialDecon(spe_tmm) : could not find function "prepareSpatialDecon"*
R Version: 
*R version 4.2.1 (2022-06-23 ucrt)*
Package Version: 
*SpatialDecon(1.8.0)*

I would greatly appreciate any guidance or suggestions on how to resolve this issue. 
Thank you for your time and assistance.

Best regards,

Zoé G

**Comment by ningbioinfo** [comment]
Hi @ZoeGerber , can you double check your standR version? Make sure it's up to date, it's in v1.6 in Bioconductor at the moment.
