### ISSUE TITLE
readGeoMx error in rowNames

### ISSUE THREAD

**Issue by kav-ita** [DavisLaboratory/standR#28]
Hi Ning,
I'm having issues with the readGeoMx function.
I'm using R version 4.3.2 and standR_1.6.0

This is the code I run:
spe <- readGeoMx(countFile, sampleAnnoFile, featureAnnoFile)

This is the error message I receive:
Error in .rowNamesDF<-(x, value = value) :
duplicate 'row.names' are not allowed
7. stop("duplicate 'row.names' are not allowed")
6..rowNamesDF<-(x, value = value)
5.row.names<-.data.frame(*tmp*, value = value)
4.row.names<-(*tmp*, value = value)
3.rownames<-(*tmp*, value = samplemeta[, colnames.as.rownames[2]])
2.geomx_import_fun(countFile, sampleAnnoFile, featureAnnoFile,
rmNegProbe, NegProbeName, colnames.as.rownames, coord.colnames)
1.readGeoMx(countFile, sampleAnnoFile, featureAnnoFile)

**Comment by kav-ita** [comment]
Found and solved issue with csv file; unrelated to package

**Comment by vmkalbskopf** [comment]
I am having the same issue. Can you explain what the issue with your csv was?

**Comment by kav-ita** [comment]
Sorry i can't remeber the specifics, but I beleive it was an issue with the countFile.
it was basically excatly what the error mentioned ie. duplicated row names
