### ISSUE TITLE
Input file for your own experiment

### ISSUE THREAD

**Issue by willros** [DavisLaboratory/standR#30]
Hi!

I have one question regarding the input files needed for running an analysis on data from your own experiment.

How do I generate the files:

* countfile: count.txt
* sampleAnnoFile: metadata.txt
* featureAnnoFile: genemeta.txt
... from my own data?

It would be really helpful if you can say something about this.

Thank you for your work!
William

**Comment by ningbioinfo** [comment]
Hi William,

In my experience with Nanostring GeoMx, they usually give you a couple of excel files that include multiple sheets.
The count table and metadata are usually in one of the sheets within the excel files.

**Comment by willros** [comment]
Thanks for answering, @ningbioinfo. 

Ok, so after the .dcc files are uploaded to the geomx machine again? I will try that later.

**Comment by hookoop** [comment]
Hey, we solved this issue!

You have to upload the DCC files to the GeoMX Data analysis suite, from where you can export an excel that contains several sheets. 
You first have to save the sheets separately, and then open them in R.
The sheets contain information for the sampleAnnoFile, feautureAnnoFile, and countfile so we subsetted them in R.

Best,
Helka

**Comment by ningbioinfo** [comment]
Hi @hookoop , thanks for the answer!

**Comment by willros** [comment]
Thanks! I found the correct files!
