### ISSUE TITLE
Inquiry about Normalization Process

### ISSUE THREAD

**Issue by jheonsuh** [DavisLaboratory/standR#35]
Hi.
Thank you for developing helpful package for analysing GeoMx datasets.
I have question that the vignette does not say in detail.

![image](https://github.com/DavisLaboratory/standR/assets/129248133/f4ef6847-1fcf-46ed-89e7-c72ecbef9a68)
![스크린샷 2024-05-11 103042](https://github.com/DavisLaboratory/standR/assets/129248133/058ebb70-ba2d-4e45-9865-c450aa4827e6)

After normalizing my dataset
using 

spe_tmm <- geomxNorm(spe, method = "TMM")

How can I check the "Normalized" value of my initial dataset, which may be contained in "spe_tmm" object. 

Since I need every single normalized value of gene counts, I wonder how can I check those.

It would be really grateful if you kindly give any advice about my question.

Thank you.

**Comment by ningbioinfo** [comment]
`assay(spe_tmm, "logcounts")`
