### ISSUE TITLE
Normalization method inquiry

### ISSUE THREAD

**Issue by jheonsuh** [DavisLaboratory/standR#36]
Hi. I am very at the beginning of analyzing GeoMx data using R.

Although GeoMx plaform provide Q3 normalization method, it is not sufficienct .
Therefore, we are trying to normalize our data using StandR packages.

I wonder how can I get a normalized gene count values of each ROIs in StandR package.

I'd like to adjust TMM, or other normalizing method to our initial data using StandR.

How can I do it? 

Can you show me any example codes ?

**Comment by ningbioinfo** [comment]
close as it's a duplicated one.
