### ISSUE TITLE
Figure legend for `plotPairPCA` exceeds plot dimensions if multiple attributes used

### ISSUE THREAD

**Issue by dkcoxie** [DavisLaboratory/standR#39]
For the `plotPairPCA` function, when plotting with multiple attributes (e.g. shape and color) the figure legend along the top can extend past the plot limits and is difficult to read. Since the common figure legend is set by a call to `ggpubr::ggarrange`, there doesn't seem to be a straightforward way to modify the figure legend location after the plot is generated.

I have made a [pull request](https://github.com/DavisLaboratory/standR/pull/38) to alter the pairedPCA plotting function to add an argument for allow the figure legend location to be specified in the function, with a default value of "top". I tested the modified code locally to ensure it had the expected functionality.

**Comment by ningbioinfo** [comment]
Thanks, pull request merged. Will be available in the devel version or the next release of BioC.

**Comment by vmkalbskopf** [comment]
Has this been released?
