### ISSUE TITLE
connection to NanoStringGeoMxSet object

### ISSUE THREAD

**Issue by inijman** [DavisLaboratory/standR#4]
HI, very interested in this approach/tool. However, the provided nanostring/Geomxtools work with a different class object (ExpressionSet, see https://bioconductor.org/packages/release/bioc/vignettes/GeomxTools/inst/doc/Developer_Introduction_to_the_NanoStringGeoMxSet.html) and we've build a full workflow around this.

Can you provide some guidance on how to use this tool on the ExpressionSet object ?

**Comment by ningbioinfo** [comment]
Hi, the standR package is using the spatialExperiment infrastructure, which is essentially a summarisedExperiment object, I found this function `makeSummarizedExperimentFromExpressionSet` from the SummarizedExperiment package. So perhaps you can try this on your object to see if that help?

Or, we have a function (`readGeoMxFromDGE`) in the package to generate the desired object from a DGEList, a DGEList can be generated from a ExpressionSet object followed by the instruction here: https://www.oreilly.com/library/view/r-bioinformatics-cookbook/9781789950694/e8903b89-b500-4c45-b0cf-345e63e2c643.xhtml
