### ISSUE TITLE
ReadGeoMx Issues

### ISSUE THREAD

**Issue by ava-amidei** [DavisLaboratory/standR#40]
Hi there. I am uploading files that I downloaded from the Nanostring Geomx DSP Analysis platform but can't get them to be read by GeoMx. I have been trying to de-bug this for a few days now and can't seem to figure out what is going wrong. I have re-uploaded them as a txt, csv, xlxs, and tsv. I am confused on how you get from the nanostring excel files to turning them into a spatial experiment object to be read by R studio.  I have followed the vingettes for StandR and readGeoMx but must be missing something. Could someone explain how they convert the excel files from nanostring into something read-able? 

Any help would be greatly appreciated. I am in my first month of graduate school and could use the help.

**Comment by zhen-fu** [comment]
If you have not seen this resource, it has more details: https://davislaboratory.github.io/GeoMXAnalysisWorkflow/articles/GeoMXAnalysisWorkflow.html. Without your error message, it is hard to tell which step and which data frame is having issues.

**Comment by ningbioinfo** [comment]
If you already have the excel files, then the process should be smooth.
Simply find out whcih sheet is the count table, sample metadata, and gene metadata (optional). Then save them as tsv files (tab as delimiters). Then they should be directly read into R using readGeoMx. Alternatively, save them as csv/txt/tsv files, read them into dataframe object in R, then use the readGeoMx function to create a SpatialExperiment object based on the data.frames that already in the R enviornment.
