### ISSUE TITLE
Unclear how sampleAnnoFile & featureAnnoFile are derived (arguments to readGeoMx function)

### ISSUE THREAD

**Issue by cjstepek** [DavisLaboratory/standR#8]
I have GeoMx NGS data. I am trying to read in data with readGeoMx in order to perform batch correction. I can generate the count matrix, however, it is unclear where the other files required for this function can be found or how they can be generated.

**Comment by cillian-gartlan** [comment]
I'm also struggling to use the readGeoMx function, which I think is down to how I have structured the sampleAnnoFile & featureAnnoFile. I understand that the data must be structured in the 'SpatialExperiment' class. Are there any examples of the correct format for these two files that I could use to make sure my data has been structured correctly?

**Comment by ningbioinfo** [comment]
Hi @cjstepek and @cillian-gartlan , the sampleAnnoFile is the annotation associating with the samples/ROIs while the featureAnnoFile is associating with genes/markers. They usually are one of the Excel sheets if you get your data from Nanostring. As an example, you can see the sample and feature annotation file in this publicly available GeoMx dataset: http://nanostring-public-share.s3-website-us-west-2.amazonaws.com/GeoScriptHub/KidneyDataset/
